#!/usr/bin/python3
# EASY-INSTALL-ENTRY-SCRIPT: 'pt-selection-pkg','console_scripts','data_generation_node'
__requires__ = 'pt-selection-pkg'
import re
import sys
from pkg_resources import load_entry_point

if __name__ == '__main__':
    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])
    sys.exit(
        load_entry_point('pt-selection-pkg', 'console_scripts', 'data_generation_node')()
    )
